apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sigterm
  labels:
    name:  signal-deploy
spec:
  selector:
    matchLabels:
      name: signal-pod
  replicas: 1
  template:
    metadata:
      labels:
        name:  signal-pod
    spec:
      containers:
      - image:  moficodes/os-signal:v0.0.2
        name:  os-signal
        imagePullPolicy: Always
      restartPolicy: Always