apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sigterm-rouge
  labels:
    name:  signal-deploy
spec:
  selector:
    matchLabels:
      name: rouge-pod
  replicas: 1
  template:
    metadata:
      labels:
        name:  rouge-pod
    spec:
      containers:
      - image:  moficodes/os-signal:vROUGE
        name:  os-signal
        imagePullPolicy: Always
      restartPolicy: Always