apiVersion: v1
kind: Service
metadata:
  name: init-container-service
spec:
  selector:
    app: init-container
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer