apiVersion: apps/v1
kind: Deployment
metadata:
  name:  resource-quotas-burstable
  labels:
    name: burstable
spec:
  selector:
    matchLabels:
      name: burstable-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: burstable-pod
    spec:
      containers:
      - image:  nginx
        name:  nginx
        imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
      restartPolicy: Always