apiVersion: apps/v1
kind: Deployment
metadata:
  name:  private
  labels:
    name:  private-deploy
spec:
  selector:
    matchLabels:
      name: private-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: private-pod
    spec:
      containers:
      - image:  us.icr.io/<YOUR-NAMESPACE>/os-signal:0.0.1
        name:  os-signal
        imagePullPolicy: Always
      # imagePullSecrets:
      #   - name: private-docker-secret
      restartPolicy: Always